"""双语字符串表：渲染器正文全部走 tr() 取文案。

规则：
- zh 为源语言；meta.language 以 "en" 开头时全文切换英文
- 英文表缺失的键自动回退中文（保证新功能先落 zh 再补 en）
- 校验诊断与 CLI JSON 消息刻意保持中文，不走本表
"""

STRINGS = {
    "zh": {
        # fallbacks
        "title_fallback": "旅行攻略",
        "subtitle": "来源可查 · 节奏适配 · 估算有标记",
        "not_specified": "未注明",
        "mode_fallback": "交通",
        # meta block
        "destination_label": "目的地：{}",
        "dates_line": "日期：{}（如为假设请核对）",
        "travelers_line": "人数：{}",
        "days_unit": "{} 天",
        "people_unit": "{} 人",
        # headings
        "assumptions": "假设与待确认",
        "route": "总体路线",
        "hotels": "住宿推荐",
        "food_businesses": "餐饮店铺推荐",
        "other_businesses": "其他商家/服务推荐",
        "transport": "交通",
        "avoid": "避坑与替代",
        "warnings": "待核实与警告",
        "checklist": "行前清单",
        "evidence": "证据卡",
        "backup": "备选方案",
        "md_images": "图文素材",
        "md_foods": "美食",
        "md_budget": "预算",
        "md_tips": "出行提示",
        "md_sources": "来源",
        "h_images": "图文",
        "h_foods": "美食推荐",
        "h_budget": "预算估算",
        "h_tips": "提示与避坑",
        "h_sources": "研究来源",
        # route
        "route_overview_fallback": "路线示意（非比例）",
        "route_order_line": "路线顺序（非比例）：{}",
        "minutes_short": "约{}分钟",
        "minutes_html": "约 {} 分钟",
        "minutes_compact": "，约{}分钟",
        "duration_unverified": "时长待核实",
        "km_short": "；约{}公里",
        "km_html": " · 约 {} 公里",
        "km_compact": "，约{}公里",
        "distance_unverified": "里程待核实",
        "distance_unverified_html": " · 里程待核实",
        "distance_unverified_compact": "，里程待核实",
        "estimate_note": "（估算，非实时导航）",
        "estimate_note_html": " · 估算，非实时导航",
        "estimate_paren": "（估算）",
        "route_note_html": "路线顺序示意，不按地理比例绘制；时长以来源和标记为准。",
        "route_caption_scaled": "路线示意 · 按坐标比例 · 等距圆柱投影 · 非导航",
        "route_aria_scaled": "总体路线位置示意，按坐标比例，非导航",
        "route_caption_chain": "路线示意 · 非比例 · 非导航",
        "route_aria_chain": "总体路线顺序示意，非比例",
        "md_leg_line": "{}. **{} → {}**：{}{}{}{}",
        "part_join": "；",
        "md_leg_notes": "   - {}",
        "source_line": "   - 来源：{}",
        # images
        "image_title_fallback": "图片",
        "image_missing_html": "图片素材缺失或格式不支持，未嵌入。",
        "image_alt_fallback": "旅行图片",
        "image_note_html": "仅嵌入用户提供并确认可使用的本地图片。",
        # days / items
        "day_heading": "Day {} · {} ({})",
        "day_heading_html": "Day {} · {}",
        "backup_line": "{}- 备选：{}",
        "backup_cond_line": "{}- 备选{}：{}",
        "condition_parens": "（{}）",
        "estimated_tag": " [估算]",
        "description_join": " — ",
        "transfer_md": "（前序接驳：{}{}{}）",
        "transfer_html": "前序接驳：{} · {}{}{}",
        "source_html": "来源：{}",
        "price_html": "参考花费：{} {}",
        "price_user_note": "（用户经验，可能变化）",
        "confidence_html": "置信度：{}",
        # transport
        "md_transport_line": "- **{}**：{}{}",
        "md_transport_price": "；费用：{}",
        # hotels / foods / businesses
        "checked_confidence_line": "  - 信息核实日期：{}；置信度：{}",
        "md_reason_join": "：{}",
        "businesses_note_html": "营业、价格和可用性应以出行当日商家信息为准；推荐不代表预订。",
        "b_address": "地址",
        "b_hours": "营业时间",
        "b_phone": "电话",
        "b_price": "价格",
        "b_checked": "核实日期",
        # avoid
        "avoid_line": "- 避免：{}；建议：{}",
        "avoid_html_prefix": "避免：",
        "suggest_html_prefix": "建议：",
        # budget
        "budget_total_label": "合计",
        "budget_pending": "待估算",
        "budget_md_line": "- **{}**：{}",
        "budget_md_category": "  - {}：{}",
        "budget_note_html": "预算为估算，须按出行日期与实际报价核实。",
        # checklist
        "checklist_date_md": "（限 {}）",
        "checklist_detail_join": "：{}",
        "checklist_note_html": "清单为提醒事项，不包含自动预订或实时核验。",
        # warnings
        "warning_line_md": "- **{}**：{}",
        "warning_line_html": "{}：{}",
        # evidence
        "evidence_fallback": "证据",
        "ev_topic": "主题",
        "ev_summary": "摘要",
        "ev_status": "状态",
        "ev_caveat": "局限",
        "ev_confidence": "置信度",
        "ev_checked": "核实日期",
        "md_kv_line": "  - {}：{}",
        # sources
        "source_type_checked_md": "（类型：{}；核实：{}）",
        "source_type_checked_html": "{} · 核实：{}",
        "sources_note_html": "小红书签名链接可能需要登录且会过期；可在 App 中搜索笔记原题。票价、开放、天气、交通和安全信息请出发前核验。",
        "footer_html": "由 TripTonic 生成。用户分享属于体验证据，不等同于官方或实时信息。",
        # stats
        "stats": "行程统计",
        "stats_pace_label": "节奏评估",
        "stats_days": "总天数",
        "stats_days_value": "{} 天",
        "stats_items": "活动项",
        "stats_items_value": "{} 个",
        "stats_meals": "餐食安排",
        "stats_drive": "自驾总时长",
        "stats_drive_km": "自驾总里程",
        "stats_longest_leg": "最长单段",
        "stats_avg_span": "日均时间跨度",
        "stats_hours": "{} 小时 {} 分",
        "stats_km": "约{}公里",
        "stats_none": "无",
        "stats_line": "- {}：{}",
        "stats_line_html": "<tr><td>{}</td><td>{}</td></tr>",
        "stats_pace": "节奏评估：{}",
        "stats_pace_ok": "符合 {} 偏好",
        "stats_pace_over": "超过 {} 建议强度",
        "stats_pace_unknown": "未设置节奏偏好",
        "stats_legend": "图例",
        "stats_gantt_title": "每日时间分布（按行程时刻）",
        "stats_gantt_aria": "每日行程时间分布图",
        "stats_budget_title": "预算构成：{}",
        "stats_budget_aria": "预算构成图",
        "t_spot": "景点",
        "t_meal": "餐食",
        "t_transport": "交通",
        "t_hotel": "住宿",
        "t_activity": "活动",
        "t_rest": "休息",
        # geojson / kml
        "geojson_route_line": "总体路线连线（按停靠顺序，非道路导航）",
        # ics
        "ics_item": "行程",
        "ics_checklist": "清单：{}",
        "ics_alarm": "提前 30 分钟出发提醒",
        "ics_transfer": "接驳：{} {}",
        "ics_minutes": "{} 分钟",
        "ics_sources": "来源：{}",
        # online map
        "online_map_title": "在线地图（需联网，非导航）",
        "online_map_note": "该地图由 Leaflet 联网渲染，离线打开时不会加载；仅作位置示意，不作为导航使用。",
        # media links
        "h_media": "媒体与视频链接",
        "media_note_html": "链接为研究时来源笔记返回的图片/视频地址；小红书签名链接可能需要登录且会过期，失效时可在 App 中搜索来源笔记原题。媒体版权归原作者，本攻略仅提供链接、不嵌入或复制媒体文件。",
        "media_note_md": "媒体链接来自来源笔记返回的图片/视频地址；签名链接可能需要登录且会过期；版权归原作者，仅作链接不嵌入。",
        "media_type_image": "图片",
        "media_type_video": "视频",
        "media_desc_fallback": "来源笔记媒体",
        "media_open_link": "打开媒体链接",
        "media_source_note": "来自：{}",
        "media_line_md": "- **[{}]** {} — [{}]({})",
        "media_from_md": "  - {}",
        "media_from_label": "来自：",
        "media_local_md": "  - [本地缓存视频]({})",
        "media_group_count": "{} 项",
        "media_cached_note_html": "已缓存的媒体已本地化：图片直接内嵌本页，视频为本目录 media/ 下的本地文件，离线可看、不会因签名链接过期而消失（保存时请连同 media/ 目录一起保留）。版权归原作者，缓存仅供个人参考，请勿再分发。未缓存的条目仍为外部链接。",
        "stats_media": "媒体链接",
    },
    "en": {
        # fallbacks
        "title_fallback": "Travel Guide",
        "subtitle": "Source-traceable · pace-matched · estimates flagged",
        "not_specified": "not specified",
        "mode_fallback": "transport",
        # meta block
        "destination_label": "Destination: {}",
        "dates_line": "Dates: {} (verify if assumed)",
        "travelers_line": "Travelers: {}",
        "days_unit": "{} days",
        "people_unit": "{} travelers",
        # headings
        "assumptions": "Assumptions & Open Questions",
        "route": "Overall Route",
        "hotels": "Lodging",
        "food_businesses": "Food & Cafés",
        "other_businesses": "Other Businesses & Services",
        "transport": "Transport",
        "avoid": "Pitfalls & Alternatives",
        "warnings": "Unresolved Checks & Warnings",
        "checklist": "Pre-trip Checklist",
        "evidence": "Evidence Cards",
        "backup": "Backup Options",
        "md_images": "Photos",
        "md_foods": "Food",
        "md_budget": "Budget",
        "md_tips": "Travel Tips",
        "md_sources": "Sources",
        "h_images": "Photos",
        "h_foods": "Food Recommendations",
        "h_budget": "Budget Estimates",
        "h_tips": "Tips & Cautions",
        "h_sources": "Research Sources",
        # route
        "route_overview_fallback": "Route sketch (not to scale)",
        "route_order_line": "Stop order (not to scale): {}",
        "minutes_short": "~{} min",
        "minutes_html": "~ {} min",
        "minutes_compact": ", ~{} min",
        "duration_unverified": "duration unverified",
        "km_short": "; ~{} km",
        "km_html": " · ~ {} km",
        "km_compact": ", ~{} km",
        "distance_unverified": "distance unverified",
        "distance_unverified_html": " · distance unverified",
        "distance_unverified_compact": ", distance unverified",
        "estimate_note": " (estimate, not live navigation)",
        "estimate_note_html": " · estimate, not live navigation",
        "estimate_paren": " (estimate)",
        "route_note_html": "Stop order is schematic and not geographically scaled; durations follow sources and flags.",
        "route_caption_scaled": "Route sketch · coordinate-proportional · equirectangular · not for navigation",
        "route_aria_scaled": "Overall route positions, coordinate-proportional, not for navigation",
        "route_caption_chain": "Route sketch · not to scale · not navigation",
        "route_aria_chain": "Overall route order, not to scale",
        "md_leg_line": "{}. **{} → {}**: {}{}{}{}",
        "part_join": "; ",
        "md_leg_notes": "   - {}",
        "source_line": "   - Source: {}",
        # images
        "image_title_fallback": "Photo",
        "image_missing_html": "Image asset missing or unsupported format; not embedded.",
        "image_alt_fallback": "Travel photo",
        "image_note_html": "Only user-supplied, approved local images are embedded.",
        # days / items
        "day_heading": "Day {} · {} ({})",
        "day_heading_html": "Day {} · {}",
        "backup_line": "{}- Backup: {}",
        "backup_cond_line": "{}- Backup{}: {}",
        "condition_parens": " ({})",
        "estimated_tag": " [estimated]",
        "description_join": " — ",
        "transfer_md": " (transfer: {}{}{})",
        "transfer_html": "Transfer: {} · {}{}{}",
        "source_html": "Source: {}",
        "price_html": "Reference cost: {} {}",
        "price_user_note": " (user-reported, may change)",
        "confidence_html": "Confidence: {}",
        # transport
        "md_transport_line": "- **{}**: {}{}",
        "md_transport_price": "; cost: {}",
        # hotels / foods / businesses
        "checked_confidence_line": "  - Checked: {}; confidence: {}",
        "md_reason_join": ": {}",
        "businesses_note_html": "Hours, prices and availability should be confirmed on the day; recommendations are not bookings.",
        "b_address": "Address",
        "b_hours": "Hours",
        "b_phone": "Phone",
        "b_price": "Price",
        "b_checked": "Checked",
        # avoid
        "avoid_line": "- Avoid: {}; instead: {}",
        "avoid_html_prefix": "Avoid: ",
        "suggest_html_prefix": "Instead: ",
        # budget
        "budget_total_label": "Total",
        "budget_pending": "to be estimated",
        "budget_md_line": "- **{}**: {}",
        "budget_md_category": "  - {}: {}",
        "budget_note_html": "Budgets are estimates; verify against real quotes for your dates.",
        # checklist
        "checklist_date_md": " (by {})",
        "checklist_detail_join": ": {}",
        "checklist_note_html": "The checklist is a reminder list; no automatic booking or live verification.",
        # warnings
        "warning_line_md": "- **{}**: {}",
        "warning_line_html": "{}: {}",
        # evidence
        "evidence_fallback": "Evidence",
        "ev_topic": "Topic",
        "ev_summary": "Summary",
        "ev_status": "Status",
        "ev_caveat": "Caveat",
        "ev_confidence": "Confidence",
        "ev_checked": "Checked",
        "md_kv_line": "  - {}: {}",
        # sources
        "source_type_checked_md": " (type: {}; checked: {})",
        "source_type_checked_html": "{} · checked: {}",
        "sources_note_html": "Signed Xiaohongshu links may require login and expire; search the note title in the app. Verify tickets, hours, weather, transport and safety before departure.",
        "footer_html": "Generated by TripTonic. User posts are experience evidence, not official or live data.",
        # stats
        "stats": "Trip Statistics",
        "stats_pace_label": "Pace assessment",
        "stats_days": "Days",
        "stats_days_value": "{}",
        "stats_items": "Activities",
        "stats_items_value": "{}",
        "stats_meals": "Meal slots",
        "stats_drive": "Total driving time",
        "stats_drive_km": "Total driving distance",
        "stats_longest_leg": "Longest leg",
        "stats_avg_span": "Average daily span",
        "stats_hours": "{}h {}m",
        "stats_km": "~{} km",
        "stats_none": "none",
        "stats_line": "- {}: {}",
        "stats_line_html": "<tr><td>{}</td><td>{}</td></tr>",
        "stats_pace": "Pace assessment: {}",
        "stats_pace_ok": "matches the {} preference",
        "stats_pace_over": "exceeds the {} limits",
        "stats_pace_unknown": "no pace preference set",
        "stats_legend": "Legend",
        "stats_gantt_title": "Daily time distribution (itinerary clock)",
        "stats_gantt_aria": "Daily itinerary time distribution chart",
        "stats_budget_title": "Budget breakdown: {}",
        "stats_budget_aria": "Budget breakdown chart",
        "t_spot": "Visit",
        "t_meal": "Meal",
        "t_transport": "Transit",
        "t_hotel": "Stay",
        "t_activity": "Activity",
        "t_rest": "Rest",
        # geojson / kml
        "geojson_route_line": "Overall route line (stop order, not road navigation)",
        # ics
        "ics_item": "Item",
        "ics_checklist": "Checklist: {}",
        "ics_alarm": "Reminder: leave 30 minutes early",
        "ics_transfer": "Transfer: {} {}",
        "ics_minutes": "{} min",
        "ics_sources": "Sources: {}",
        # online map
        "online_map_title": "Online map (network required, not navigation)",
        "online_map_note": "Rendered online by Leaflet; not loaded when offline. Position sketch only, not navigation.",
        # media links
        "h_media": "Media & Video Links",
        "media_note_html": "Links point to image/video addresses returned by the source notes during research; signed Xiaohongshu links may require login and expire — search the source note title in the app if a link fails. Media belongs to its original authors; this guide links only, never embeds or copies media files.",
        "media_note_md": "Media links come from image/video addresses returned by source notes; signed links may require login and expire. Media belongs to its authors; linked, not embedded.",
        "media_type_image": "Image",
        "media_type_video": "Video",
        "media_desc_fallback": "Source note media",
        "media_open_link": "Open media link",
        "media_source_note": "From: {}",
        "media_line_md": "- **[{}]** {} — [{}]({})",
        "media_from_md": "  - {}",
        "media_from_label": "From: ",
        "media_local_md": "  - [Local cached video]({})",
        "media_group_count": "{} media",
        "media_cached_note_html": "Cached media is localized: images are embedded inline, videos live as local files under media/ next to this page, so they survive offline and signed-link expiry (keep the media/ folder when saving). Copyright belongs to the original authors; cached for personal reference only, do not redistribute. Uncached entries remain external links.",
        "stats_media": "Media links",
    },
}


def guide_language(guide):
    """解析 guide 的渲染语言："en"（英文）或 "zh"（默认中文）。"""
    language = str((guide.get("meta") or {}).get("language", "zh-CN")).strip().lower()
    return "en" if language.startswith("en") else "zh"


def tr(guide, key):
    """按 guide 语言取文案；英文表缺键时回退中文源表。"""
    language = guide_language(guide)
    table = STRINGS[language]
    if key in table:
        return table[key]
    return STRINGS["zh"][key]
